parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

env:
  es6: true
  browser: true
  commonjs: true

plugins: ['react']
extends: ['htmlacademy/es6', 'plugin:react/recommended']
settings:
  react:
    version: '16'
